### ISSUE TITLE
error: no member named 'statfs_x' in 'fuse_operations'

### ISSUE THREAD

**Issue by jtsylve** [tienex/apfs#1]
When I try to compile on OS X 10.12.6 I get the following error

```
apfs/mount/fuse_bridge.cpp:304:18: error: no member named 'statfs_x' in 'fuse_operations'
        fuse_ops.statfs_x   = apfs_statfs;
```

Below is the full output:

```
bbmbp080:apfs joe$ cmake CMakeLists.txt 
-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test _APPLE_C_x86_64
-- Performing Test _APPLE_C_x86_64 - Success
-- Performing Test _APPLE_CXX_x86_64
-- Performing Test _APPLE_CXX_x86_64 - Success
-- Architecture x86_64 supported
-- Performing Test _APPLE_C_i386
-- Performing Test _APPLE_C_i386 - Success
-- Performing Test _APPLE_CXX_i386
-- Performing Test _APPLE_CXX_i386 - Success
-- Architecture i386 supported
-- Looking for libxo/xo.h
-- Looking for libxo/xo.h - not found
-- Looking for xo.h
-- Looking for xo.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for stdio_ext.h
-- Looking for stdio_ext.h - not found
-- Looking for libutil.h
-- Looking for libutil.h - not found
-- Looking for sys/un.h
-- Looking for sys/un.h - found
-- Looking for sys/syslog.h
-- Looking for sys/syslog.h - found
-- Looking for __flbf
-- Looking for __flbf - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for dlfunc
-- Looking for dlfunc - not found
-- Looking for syslog
-- Looking for syslog - found
-- Looking for __isthreaded
-- Looking for __isthreaded - not found
-- Performing Test HAVE_SUN_LEN
-- Performing Test HAVE_SUN_LEN - Success
-- Performing Test HAVE_THREAD_LOCAL_before
-- Performing Test HAVE_THREAD_LOCAL_before - Success
-- Performing Test HAVE_THREAD_LOCAL_after
-- Performing Test HAVE_THREAD_LOCAL_after - Success
-- Looking for include files sys/types.h, sys/xattr.h
-- Looking for include files sys/types.h, sys/xattr.h - found
-- Looking for include files sys/types.h, sys/extattr.h
-- Looking for include files sys/types.h, sys/extattr.h - not found
-- Looking for include files sys/types.h, sys/disk.h
-- Looking for include files sys/types.h, sys/disk.h - found
-- Looking for include files sys/types.h, sys/dkio.h
-- Looking for include files sys/types.h, sys/dkio.h - not found
-- Looking for include files sys/types.h, sys/disklabel.h
-- Looking for include files sys/types.h, sys/disklabel.h - not found
-- Looking for include files sys/types.h, sys/disklabel32.h
-- Looking for include files sys/types.h, sys/disklabel32.h - not found
-- Looking for include files sys/types.h, sys/disklabel64.h
-- Looking for include files sys/types.h, sys/disklabel64.h - not found
-- Looking for include files sys/types.h, sys/diskslice.h
-- Looking for include files sys/types.h, sys/diskslice.h - not found
-- Looking for include files sys/types.h, sys/time.h
-- Looking for include files sys/types.h, sys/time.h - found
-- Looking for include files sys/types.h, sys/utime.h
-- Looking for include files sys/types.h, sys/utime.h - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of struct timespec
-- Check size of struct timespec - done
-- Looking for getopt
-- Looking for getopt - found
-- Looking for ftruncate
-- Looking for ftruncate - found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for _futime64
-- Looking for _futime64 - not found
-- Looking for _futime
-- Looking for _futime - not found
-- Looking for fchflags
-- Looking for fchflags - found
-- Looking for fsetxattr
-- Looking for fsetxattr - found
-- Looking for extattr_set_fd
-- Looking for extattr_set_fd - not found
-- Looking for extattr_set_file
-- Looking for extattr_set_file - not found
-- Looking for attropen
-- Looking for attropen - not found
-- Looking for fsetea
-- Looking for fsetea - not found
-- Looking for _chsize
-- Looking for _chsize - not found
-- Looking for chsize
-- Looking for chsize - not found
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Looking for symlink
-- Looking for symlink - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for C++ include codecvt
-- Looking for C++ include codecvt - found
-- Looking for include files sys/types.h, sys/param.h
-- Looking for include files sys/types.h, sys/param.h - found
-- Looking for include files sys/types.h, sys/mkdev.h
-- Looking for include files sys/types.h, sys/mkdev.h - not found
-- Looking for include files sys/types.h, sys/mount.h
-- Looking for include files sys/types.h, sys/mount.h - found
-- Looking for include files sys/types.h, sys/statfs.h
-- Looking for include files sys/types.h, sys/statfs.h - not found
-- Looking for include files sys/types.h, sys/statvfs.h
-- Looking for include files sys/types.h, sys/statvfs.h - found
-- Looking for include files sys/types.h, sys/sysmacros.h
-- Looking for include files sys/types.h, sys/sysmacros.h - not found
-- Looking for include files sys/types.h, sys/vfs.h
-- Looking for include files sys/types.h, sys/vfs.h - not found
-- Check size of struct statfs
-- Check size of struct statfs - done
-- Check size of struct statvfs
-- Check size of struct statvfs - done
-- Performing Test HAVE_STATFS_F_BAVAIL_IN_SYS_MOUNT_H
-- Performing Test HAVE_STATFS_F_BAVAIL_IN_SYS_MOUNT_H - Success
-- Performing Test HAVE_STATFS_F_IOSIZE_IN_SYS_MOUNT_H
-- Performing Test HAVE_STATFS_F_IOSIZE_IN_SYS_MOUNT_H - Success
-- Performing Test HAVE_STATFS_F_FRSIZE_IN_SYS_MOUNT_H
-- Performing Test HAVE_STATFS_F_FRSIZE_IN_SYS_MOUNT_H - Failed
-- Performing Test HAVE_STATFS_F_FLAG_IN_SYS_MOUNT_H
-- Performing Test HAVE_STATFS_F_FLAG_IN_SYS_MOUNT_H - Failed
-- Performing Test HAVE_STATFS_F_FLAGS_IN_SYS_MOUNT_H
-- Performing Test HAVE_STATFS_F_FLAGS_IN_SYS_MOUNT_H - Success
-- Performing Test HAVE_STATVFS_F_FLAG
-- Performing Test HAVE_STATVFS_F_FLAG - Success
-- Performing Test HAVE_STATVFS_F_FLAGS
-- Performing Test HAVE_STATVFS_F_FLAGS - Failed
-- Performing Test HAVE_STAT_ST_MTIM
-- Performing Test HAVE_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STAT_ST_MTIMENSEC
-- Performing Test HAVE_STAT_ST_MTIMENSEC - Failed
-- Performing Test HAVE_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STAT_ST_MTIMESPEC - Success
-- Performing Test HAVE_STAT_ST_BIRTHTIME
-- Performing Test HAVE_STAT_ST_BIRTHTIME - Success
-- Performing Test HAVE_STAT___ST_BIRTHTIME
-- Performing Test HAVE_STAT___ST_BIRTHTIME - Failed
-- Performing Test HAVE_STAT_ST_BIRTHTIMENSEC
-- Performing Test HAVE_STAT_ST_BIRTHTIMENSEC - Failed
-- Performing Test HAVE_STAT_ST___BIRTHTIMENSEC
-- Performing Test HAVE_STAT_ST___BIRTHTIMENSEC - Failed
-- Performing Test HAVE_STAT_ST_BIRTHTIM
-- Performing Test HAVE_STAT_ST_BIRTHTIM - Failed
-- Performing Test HAVE_STAT___ST_BIRTHTIM
-- Performing Test HAVE_STAT___ST_BIRTHTIM - Failed
-- Performing Test HAVE_STAT_ST_BIRTHTIMESPEC
-- Performing Test HAVE_STAT_ST_BIRTHTIMESPEC - Success
-- Performing Test HAVE_STAT_ST_BLKSIZE
-- Performing Test HAVE_STAT_ST_BLKSIZE - Success
-- Performing Test HAVE_STAT_ST_BLOCKS
-- Performing Test HAVE_STAT_ST_BLOCKS - Success
-- Performing Test HAVE_STAT_ST_FLAGS
-- Performing Test HAVE_STAT_ST_FLAGS - Success
-- Performing Test FUSE_CFLAGS_CHECK
-- Performing Test FUSE_CFLAGS_CHECK - Failed
-- Found FUSE: /usr/local/lib/libosxfuse.dylib  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/joe/src/apfs
bbmbp080:apfs joe$ make -j8
Scanning dependencies of target nx_table
Scanning dependencies of target nx_xo
Scanning dependencies of target nxcompat
[  1%] Building C object third_party/libtable/CMakeFiles/nx_table.dir/table.c.o
[  4%] Building C object third_party/libxo/CMakeFiles/nx_xo.dir/libxo/libxo/xo_encoder.c.o
[  3%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/fblkinfo.c.o
[  4%] Building C object third_party/libxo/CMakeFiles/nx_xo.dir/libxo/libxo/libxo.c.o
[  6%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/fchflags.c.o
[  6%] Building C object third_party/libxo/CMakeFiles/nx_xo.dir/libxo/libxo/xo_syslog.c.o
[  7%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/fsetxattr.c.o
[  8%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/ftruncate.c.o
[  9%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/getopt.c.o
[ 10%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/futimens.c.o
[ 11%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/pread.c.o
[ 12%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/pwrite.c.o
[ 13%] Linking C static library libnx_table.a
[ 14%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/symlink.c.o
[ 15%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/winerror.c.o
[ 15%] Built target nx_table
[ 16%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/third_party/base64.c.o
[ 17%] Building C object libnxcompat/CMakeFiles/nxcompat.dir/sources/third_party/ConvertUTF.c.o
[ 18%] Linking C static library libnxcompat.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(fchflags.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(fsetxattr.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(ftruncate.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(getopt.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(pread.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(pwrite.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(symlink.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: libnxcompat.a(winerror.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(fchflags.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(fsetxattr.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(ftruncate.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(getopt.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(pread.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(pwrite.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(symlink.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: libnxcompat.a(winerror.c.o) has no symbols
[ 18%] Built target nxcompat
Scanning dependencies of target nxtools
[ 19%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/native.cpp.o
[ 20%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/string.cpp.o
[ 21%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/time.cpp.o
[ 22%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/path.cpp.o
[ 23%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/file_logger.cpp.o
[ 24%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/stderr_logger.cpp.o
[ 25%] Building CXX object libnxtools/CMakeFiles/nxtools.dir/sources/syslog_logger.cpp.o
[ 26%] Linking C static library libnx_xo.a
[ 26%] Built target nx_xo
Scanning dependencies of target nx_static
Scanning dependencies of target nx_shared
[ 28%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/btree_traverser.cpp.o
[ 28%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/container.cpp.o
[ 29%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/btree_traverser.cpp.o
[ 30%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/container.cpp.o
[ 31%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/context.cpp.o
[ 32%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/context.cpp.o
[ 33%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/device.cpp.o
[ 34%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/device.cpp.o
[ 35%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/enumerator.cpp.o
[ 36%] Linking CXX static library libnxtools.a
[ 36%] Built target nxtools
[ 37%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/enumerator.cpp.o
[ 38%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/object.cpp.o
[ 39%] Building CXX object libnx/CMakeFiles/nx_static.dir/sources/volume.cpp.o
[ 40%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/volume.cpp.o
[ 41%] Building CXX object libnx/CMakeFiles/nx_shared.dir/sources/object.cpp.o
[ 42%] Building C object libnx/CMakeFiles/nx_static.dir/sources/format/nx_dumper.c.o
[ 43%] Building C object libnx/CMakeFiles/nx_shared.dir/sources/format/nx_dumper.c.o
[ 44%] Building C object libnx/CMakeFiles/nx_shared.dir/sources/format/nx.c.o
[ 45%] Building C object libnx/CMakeFiles/nx_static.dir/sources/format/nx.c.o
[ 46%] Building C object libnx/CMakeFiles/nx_static.dir/sources/format/nxdump.c.o
[ 47%] Building C object libnx/CMakeFiles/nx_static.dir/sources/format/apfs.c.o
[ 48%] Building C object libnx/CMakeFiles/nx_shared.dir/sources/format/nxdump.c.o
[ 49%] Building C object libnx/CMakeFiles/nx_static.dir/sources/format/apfsdump.c.o
[ 50%] Building C object libnx/CMakeFiles/nx_shared.dir/sources/format/apfs.c.o
[ 51%] Building C object libnx/CMakeFiles/nx_shared.dir/sources/format/apfsdump.c.o
[ 52%] Linking CXX static library libnx.a
[ 53%] Linking CXX shared library libnx.dylib
[ 53%] Built target nx_static
Scanning dependencies of target apfs_static
[ 57%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/internal/xattr.cpp.o
[ 57%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/internal/directory.cpp.o
[ 57%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/internal/object_cache.cpp.o
[ 57%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/internal/object.cpp.o
[ 58%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/internal/file.cpp.o
[ 60%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/session.cpp.o
[ 60%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/volume.cpp.o
[ 60%] Built target nx_shared
Scanning dependencies of target apfs_shared
[ 61%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/internal/directory.cpp.o
Scanning dependencies of target apfs_probe
Scanning dependencies of target nx_probe
[ 62%] Building CXX object tools/CMakeFiles/apfs_probe.dir/apfs_probe.cpp.o
[ 63%] Building CXX object tools/CMakeFiles/nx_probe.dir/nx_probe.cpp.o
[ 64%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/internal/file.cpp.o
[ 65%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/internal/object.cpp.o
[ 66%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/internal/object_cache.cpp.o
[ 67%] Building CXX object libapfs/CMakeFiles/apfs_static.dir/sources/object.cpp.o
[ 68%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/internal/xattr.cpp.o
[ 69%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/session.cpp.o
[ 70%] Linking CXX executable apfs_probe
[ 71%] Linking CXX executable nx_probe
[ 71%] Built target apfs_probe
[ 72%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/volume.cpp.o
[ 72%] Built target nx_probe
[ 73%] Building CXX object libapfs/CMakeFiles/apfs_shared.dir/sources/object.cpp.o
[ 74%] Linking CXX static library libapfs.a
[ 74%] Built target apfs_static
[ 75%] Linking CXX shared library libapfs.dylib
[ 75%] Built target apfs_shared
Scanning dependencies of target nx_tool
Scanning dependencies of target apfs_fuse
[ 77%] Building CXX object tools/CMakeFiles/nx_tool.dir/main.cpp.o
[ 78%] Building CXX object tools/CMakeFiles/nx_tool.dir/nx_omap.cpp.o
[ 78%] Building CXX object tools/CMakeFiles/nx_tool.dir/apfs_traverse.cpp.o
[ 80%] Building CXX object tools/CMakeFiles/nx_tool.dir/apfs_content.cpp.o
[ 81%] Building CXX object tools/CMakeFiles/nx_tool.dir/apfs_omap.cpp.o
[ 81%] Building CXX object tools/CMakeFiles/nx_tool.dir/nx_scavenge.cpp.o
[ 82%] Building CXX object tools/CMakeFiles/nx_tool.dir/apfs_extract.cpp.o
[ 82%] Building CXX object mount/CMakeFiles/apfs_fuse.dir/fuse_bridge.cpp.o
[ 83%] Building CXX object mount/CMakeFiles/apfs_fuse.dir/base.cpp.o
/Users/joe/src/apfs/mount/fuse_bridge.cpp:304:18: error: no member named 'statfs_x' in 'fuse_operations'
        fuse_ops.statfs_x   = apfs_statfs;
        ~~~~~~~~ ^
1 error generated.
make[2]: *** [mount/CMakeFiles/apfs_fuse.dir/fuse_bridge.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 84%] Linking CXX executable nx_tool
[ 84%] Built target nx_tool
Scanning dependencies of target nx_omap
Scanning dependencies of target apfs_extract
Scanning dependencies of target nx_scavenge
Scanning dependencies of target apfs_omap
Scanning dependencies of target apfs_content
Scanning dependencies of target apfs_traverse
[ 84%] Built target apfs_extract
[ 84%] Built target apfs_traverse
[ 84%] Built target nx_omap
[ 84%] Built target nx_scavenge
[ 84%] Built target apfs_content
[ 84%] Built target apfs_omap
make[1]: *** [mount/CMakeFiles/apfs_fuse.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tienex** [comment]
Statfs_x should be available from osxfuse 3.7.0, I will add a check for that, in the meantime you could try upgrading fuse or forcing the code to take the statfs path

**Comment by jtsylve** [comment]
Updating osxfuse did the trick.  A check for the version would likely prevent some confusion.
